const mongoose = require('mongoose');
const { Product } = require('../models/Product');
const { Brand } = require('../models/Brand');
require('dotenv').config();

const brandsData = [
  {
    name: 'MAC Cosmetics',
    slug: 'mac-cosmetics',
    description: 'Professional makeup artistry cosmetics',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/MAC_Cosmetics_logo.svg/200px-MAC_Cosmetics_logo.svg.png',
    website: 'https://www.maccosmetics.com',
    country: 'USA',
  },
  {
    name: 'Chanel',
    slug: 'chanel',
    description: 'French luxury fashion house and perfumes',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chanel_logo.svg/200px-Chanel_logo.svg.png',
    website: 'https://www.chanel.com',
    country: 'France',
  },
  {
    name: 'Dior',
    slug: 'dior',
    description: 'French luxury goods company',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Dior_logo.svg/200px-Dior_logo.svg.png',
    website: 'https://www.dior.com',
    country: 'France',
  },
  {
    name: 'Sephora',
    slug: 'sephora',
    description:
      'French multinational retailer of personal care and beauty products',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sephora_logo.svg/200px-Sephora_logo.svg.png',
    website: 'https://www.sephora.com',
    country: 'France',
  },
  {
    name: 'NARS Cosmetics',
    slug: 'nars-cosmetics',
    description: 'French cosmetics and beauty brand',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/NARS_logo.svg/200px-NARS_logo.svg.png',
    website: 'https://www.narscosmetics.com',
    country: 'USA',
  },
  {
    name: 'Estée Lauder',
    slug: 'estee-lauder',
    description:
      'American multinational manufacturer and marketer of prestige skincare, makeup, fragrance and hair care products',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5 5a/Estee_Lauder_logo.svg/200px-Estee_Lauder_logo.svg.png',
    website: 'https://www.esteelauder.com',
    country: 'USA',
  },
  {
    name: "L'Oréal Paris",
    slug: 'loreal-paris',
    description: 'French personal care company',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/L%27Oreal_logo.svg/200px-L%27Oreal_logo.svg.png',
    website: 'https://www.lorealparis.com',
    country: 'France',
  },
  {
    name: 'Gucci',
    slug: 'gucci',
    description: 'Italian luxury brand of fashion and leather goods',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Gucci_logo.svg/200px-Gucci_logo.svg.png',
    website: 'https://www.gucci.com',
    country: 'Italy',
  },
  {
    name: 'Prada',
    slug: 'prada',
    description: 'Italian luxury fashion house',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Prada_logo.svg/200px-Prada_logo.svg.png',
    website: 'https://www.prada.com',
    country: 'Italy',
  },
  {
    name: 'Zara',
    slug: 'zara',
    description: 'Spanish clothing retailer',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Zara_logo.svg/200px-Zara_logo.svg.png',
    website: 'https://www.zara.com',
    country: 'Spain',
  },
];

const productsData = [
  // MAC Cosmetics Products
  {
    title: 'MAC Retro Matte Liquid Lipcolour',
    brand: 'MAC Cosmetics',
    description: 'Long-wearing liquid lipstick with a matte finish',
    price: 24.0,
    basePrice: 24.0,
    cover: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500',
    category: 'makeup',
    subcategory: 'Lips',
    material: 'Liquid',
    stock: 150,
    sku: 'MAC-001',
    weight: 0.05,
    dimensions: { length: 2, width: 2, height: 8 },
    variants: [
      {
        size: 'Standard',
        color: 'Ruby Woo',
        colorCode: '#C41E3A',
        stock: 50,
        price: 24.0,
      },
      {
        size: 'Standard',
        color: 'Russian Red',
        colorCode: '#8B0000',
        stock: 50,
        price: 24.0,
      },
      {
        size: 'Standard',
        color: 'Divine Wine',
        colorCode: '#722F37',
        stock: 50,
        price: 24.0,
      },
    ],
    featured: true,
  },
  {
    title: 'MAC Studio Fix Powder Plus Foundation',
    brand: 'MAC Cosmetics',
    description: 'Professional powder foundation for all skin types',
    price: 32.0,
    basePrice: 32.0,
    cover: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=500',
    category: 'makeup',
    subcategory: 'Face',
    material: 'Powder',
    stock: 200,
    sku: 'MAC-002',
    weight: 0.1,
    dimensions: { length: 5, width: 5, height: 3 },
    variants: [
      {
        size: 'Standard',
        color: 'NC15',
        colorCode: '#F5DEB3',
        stock: 40,
        price: 32.0,
      },
      {
        size: 'Standard',
        color: 'NC25',
        colorCode: '#DEB887',
        stock: 40,
        price: 32.0,
      },
      {
        size: 'Standard',
        color: 'NC35',
        colorCode: '#D2B48C',
        stock: 40,
        price: 32.0,
      },
      {
        size: 'Standard',
        color: 'NC45',
        colorCode: '#C4A574',
        stock: 40,
        price: 32.0,
      },
      {
        size: 'Standard',
        color: 'NW20',
        colorCode: '#FFE4C4',
        stock: 40,
        price: 32.0,
      },
    ],
    featured: true,
  },
  {
    title: 'MAC Eyeshadow Palette',
    brand: 'MAC Cosmetics',
    description: 'Professional eyeshadow palette with 9 shades',
    price: 48.0,
    basePrice: 48.0,
    cover: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=500',
    category: 'makeup',
    subcategory: 'Eyes',
    material: 'Powder',
    stock: 100,
    sku: 'MAC-003',
    weight: 0.15,
    dimensions: { length: 15, width: 10, height: 2 },
    variants: [
      {
        size: '9-Pan',
        color: 'Warm Neutrals',
        colorCode: '#D2691E',
        stock: 50,
        price: 48.0,
      },
      {
        size: '9-Pan',
        color: 'Cool Tones',
        colorCode: '#708090',
        stock: 50,
        price: 48.0,
      },
    ],
    featured: false,
  },
  // Chanel Products
  {
    title: 'Chanel No. 5 Eau de Parfum',
    brand: 'Chanel',
    description: 'Iconic floral-aldehydic fragrance',
    price: 150.0,
    basePrice: 150.0,
    cover: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500',
    category: 'perfumes',
    subcategory: 'Women',
    material: 'Liquid',
    stock: 80,
    sku: 'CHN-001',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 150.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 210.0,
      },
      {
        size: '35ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 20,
        price: 125.0,
      },
    ],
    featured: true,
  },
  {
    title: 'Chanel Coco Mademoiselle',
    brand: 'Chanel',
    description: 'Fresh oriental fragrance for women',
    price: 135.0,
    basePrice: 135.0,
    cover: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500',
    category: 'perfumes',
    subcategory: 'Women',
    material: 'Liquid',
    stock: 75,
    sku: 'CHN-002',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 135.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 195.0,
      },
      {
        size: '35ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 110.0,
      },
    ],
    featured: true,
  },
  {
    title: 'Chanel Bleu de Chanel',
    brand: 'Chanel',
    description: 'Aromatic woody fragrance for men',
    price: 140.0,
    basePrice: 140.0,
    cover: 'https://images.unsplash.com/photo-1595425940377-c9703cf48b6d?w=500',
    category: 'perfumes',
    subcategory: 'Men',
    material: 'Liquid',
    stock: 70,
    sku: 'CHN-003',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 140.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 195.0,
      },
      {
        size: '35ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 20,
        price: 115.0,
      },
    ],
    featured: true,
  },
  // Dior Products
  {
    title: 'Dior Addict Lipstick',
    brand: 'Dior',
    description: 'Vibrant color and shine with a comfortable feel',
    price: 42.0,
    basePrice: 42.0,
    cover: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500',
    category: 'makeup',
    subcategory: 'Lips',
    material: 'Cream',
    stock: 120,
    sku: 'DIO-001',
    weight: 0.05,
    dimensions: { length: 2, width: 2, height: 8 },
    variants: [
      {
        size: 'Standard',
        color: '999 Rouge Dior',
        colorCode: '#8B0000',
        stock: 40,
        price: 42.0,
      },
      {
        size: 'Standard',
        color: '620 Dior Addict',
        colorCode: '#DC143C',
        stock: 40,
        price: 42.0,
      },
      {
        size: 'Standard',
        color: '560 Diorific',
        colorCode: '#800020',
        stock: 40,
        price: 42.0,
      },
    ],
    featured: true,
  },
  {
    title: 'Dior Sauvage Eau de Parfum',
    brand: 'Dior',
    description: 'Raw and noble fragrance for men',
    price: 130.0,
    basePrice: 130.0,
    cover: 'https://images.unsplash.com/photo-1595425940377-c9703cf48b6d?w=500',
    category: 'perfumes',
    subcategory: 'Men',
    material: 'Liquid',
    stock: 85,
    sku: 'DIO-002',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '60ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 130.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 175.0,
      },
      {
        size: '200ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 250.0,
      },
    ],
    featured: true,
  },
  {
    title: "Dior J'adore Eau de Parfum",
    brand: 'Dior',
    description: 'Floral fragrance for women',
    price: 145.0,
    basePrice: 145.0,
    cover: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500',
    category: 'perfumes',
    subcategory: 'Women',
    material: 'Liquid',
    stock: 90,
    sku: 'DIO-003',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 145.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 205.0,
      },
      {
        size: '35ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 120.0,
      },
    ],
    featured: true,
  },
  // Sephora Products
  {
    title: 'Sephora Collection Cream Lip Stain',
    brand: 'Sephora',
    description: 'Long-lasting liquid lip stain',
    price: 14.0,
    basePrice: 14.0,
    cover: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500',
    category: 'makeup',
    subcategory: 'Lips',
    material: 'Liquid',
    stock: 200,
    sku: 'SEP-001',
    weight: 0.05,
    dimensions: { length: 2, width: 2, height: 8 },
    variants: [
      {
        size: 'Standard',
        color: 'Always Red',
        colorCode: '#DC143C',
        stock: 50,
        price: 14.0,
      },
      {
        size: 'Standard',
        color: 'Berry Smoothie',
        colorCode: '#8B008B',
        stock: 50,
        price: 14.0,
      },
      {
        size: 'Standard',
        color: 'Pink Nude',
        colorCode: '#FFB6C1',
        stock: 50,
        price: 14.0,
      },
      {
        size: 'Standard',
        color: 'Coral Crush',
        colorCode: '#FF7F50',
        stock: 50,
        price: 14.0,
      },
    ],
    featured: false,
  },
  {
    title: 'Sephora Collection Face Palette',
    brand: 'Sephora',
    description: 'All-in-one face palette with contour, blush, and highlighter',
    price: 25.0,
    basePrice: 25.0,
    cover: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=500',
    category: 'makeup',
    subcategory: 'Face',
    material: 'Powder',
    stock: 150,
    sku: 'SEP-002',
    weight: 0.12,
    dimensions: { length: 12, width: 8, height: 2 },
    variants: [
      {
        size: 'Standard',
        color: 'Light Medium',
        colorCode: '#F5DEB3',
        stock: 50,
        price: 25.0,
      },
      {
        size: 'Standard',
        color: 'Medium Deep',
        colorCode: '#D2B48C',
        stock: 50,
        price: 25.0,
      },
      {
        size: 'Standard',
        color: 'Deep',
        colorCode: '#8B4513',
        stock: 50,
        price: 25.0,
      },
    ],
    featured: false,
  },
  // NARS Products
  {
    title: 'NARS Orgasm Blush',
    brand: 'NARS Cosmetics',
    description: 'Iconic peachy pink blush with golden shimmer',
    price: 32.0,
    basePrice: 32.0,
    cover: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=500',
    category: 'makeup',
    subcategory: 'Face',
    material: 'Powder',
    stock: 180,
    sku: 'NRS-001',
    weight: 0.08,
    dimensions: { length: 4, width: 4, height: 2 },
    variants: [
      {
        size: 'Standard',
        color: 'Orgasm',
        colorCode: '#FFB6C1',
        stock: 90,
        price: 32.0,
      },
      {
        size: 'Standard',
        color: 'Super Orgasm',
        colorCode: '#FF69B4',
        stock: 90,
        price: 32.0,
      },
    ],
    featured: true,
  },
  {
    title: 'NARS Audacious Lipstick',
    brand: 'NARS Cosmetics',
    description: 'High-impact lipstick with rich color',
    price: 28.0,
    basePrice: 28.0,
    cover: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500',
    category: 'makeup',
    subcategory: 'Lips',
    material: 'Cream',
    stock: 160,
    sku: 'NRS-002',
    weight: 0.05,
    dimensions: { length: 2, width: 2, height: 8 },
    variants: [
      {
        size: 'Standard',
        color: 'Carmen',
        colorCode: '#8B0000',
        stock: 40,
        price: 28.0,
      },
      {
        size: 'Standard',
        color: 'Anna',
        colorCode: '#DC143C',
        stock: 40,
        price: 28.0,
      },
      {
        size: 'Standard',
        color: 'Mona',
        colorCode: '#800020',
        stock: 40,
        price: 28.0,
      },
      {
        size: 'Standard',
        color: 'Barbara',
        colorCode: '#FF1493',
        stock: 40,
        price: 28.0,
      },
    ],
    featured: false,
  },
  // Estée Lauder Products
  {
    title: 'Estée Lauder Double Wear Foundation',
    brand: 'Estée Lauder',
    description: '24-hour wear foundation with full coverage',
    price: 44.0,
    basePrice: 44.0,
    cover: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=500',
    category: 'makeup',
    subcategory: 'Face',
    material: 'Liquid',
    stock: 140,
    sku: 'EST-001',
    weight: 0.1,
    dimensions: { length: 5, width: 5, height: 4 },
    variants: [
      {
        size: '30ml',
        color: '1W1 Bone',
        colorCode: '#F5DEB3',
        stock: 28,
        price: 44.0,
      },
      {
        size: '30ml',
        color: '2C1 Fresco',
        colorCode: '#DEB887',
        stock: 28,
        price: 44.0,
      },
      {
        size: '30ml',
        color: '3W1 Tawny',
        colorCode: '#D2B48C',
        stock: 28,
        price: 44.0,
      },
      {
        size: '30ml',
        color: '4W1 Sand',
        colorCode: '#C4A574',
        stock: 28,
        price: 44.0,
      },
      {
        size: '30ml',
        color: '5W1 Honey',
        colorCode: '#8B4513',
        stock: 28,
        price: 44.0,
      },
    ],
    featured: true,
  },
  {
    title: 'Estée Lauder Advanced Night Repair',
    brand: 'Estée Lauder',
    description: 'Recovery complex serum for skin repair',
    price: 105.0,
    basePrice: 105.0,
    cover: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=500',
    category: 'skincare',
    subcategory: 'Serums',
    material: 'Liquid',
    stock: 100,
    sku: 'EST-002',
    weight: 0.15,
    dimensions: { length: 5, width: 5, height: 10 },
    variants: [
      {
        size: '30ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 105.0,
      },
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 165.0,
      },
    ],
    featured: true,
  },
  // L'Oréal Paris Products
  {
    title: "L'Oréal Paris Infallible Foundation",
    brand: "L'Oréal Paris",
    description: '24-hour matte foundation',
    price: 15.0,
    basePrice: 15.0,
    cover: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=500',
    category: 'makeup',
    subcategory: 'Face',
    material: 'Liquid',
    stock: 250,
    sku: 'LRL-001',
    weight: 0.1,
    dimensions: { length: 5, width: 5, height: 4 },
    variants: [
      {
        size: '30ml',
        color: '102 Vanilla',
        colorCode: '#F5DEB3',
        stock: 50,
        price: 15.0,
      },
      {
        size: '30ml',
        color: '103 Beige',
        colorCode: '#DEB887',
        stock: 50,
        price: 15.0,
      },
      {
        size: '30ml',
        color: '104 Natural Beige',
        colorCode: '#D2B48C',
        stock: 50,
        price: 15.0,
      },
      {
        size: '30ml',
        color: '105 Golden Beige',
        colorCode: '#C4A574',
        stock: 50,
        price: 15.0,
      },
      {
        size: '30ml',
        color: '106 Warm Beige',
        colorCode: '#8B4513',
        stock: 50,
        price: 15.0,
      },
    ],
    featured: false,
  },
  {
    title: "L'Oréal Paris Revitalift Serum",
    brand: "L'Oréal Paris",
    description: 'Anti-aging serum with hyaluronic acid',
    price: 25.0,
    basePrice: 25.0,
    cover: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=500',
    category: 'skincare',
    subcategory: 'Serums',
    material: 'Liquid',
    stock: 200,
    sku: 'LRL-002',
    weight: 0.12,
    dimensions: { length: 4, width: 4, height: 12 },
    variants: [
      {
        size: '30ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 100,
        price: 25.0,
      },
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 100,
        price: 35.0,
      },
    ],
    featured: false,
  },
  // Gucci Products
  {
    title: 'Gucci Bloom Eau de Parfum',
    brand: 'Gucci',
    description: 'Floral fragrance for women',
    price: 135.0,
    basePrice: 135.0,
    cover: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500',
    category: 'perfumes',
    subcategory: 'Women',
    material: 'Liquid',
    stock: 80,
    sku: 'GUC-001',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 135.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 30,
        price: 185.0,
      },
      {
        size: '30ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 20,
        price: 110.0,
      },
    ],
    featured: true,
  },
  {
    title: 'Gucci Guilty Pour Femme',
    brand: 'Gucci',
    description: 'Contemporary fragrance for women',
    price: 125.0,
    basePrice: 125.0,
    cover: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500',
    category: 'perfumes',
    subcategory: 'Women',
    material: 'Liquid',
    stock: 75,
    sku: 'GUC-002',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 125.0,
      },
      {
        size: '90ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 175.0,
      },
      {
        size: '30ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 100.0,
      },
    ],
    featured: true,
  },
  // Prada Products
  {
    title: 'Prada Luna Rossa Carbon',
    brand: 'Prada',
    description: 'Aromatic fougère fragrance for men',
    price: 115.0,
    basePrice: 115.0,
    cover: 'https://images.unsplash.com/photo-1595425940377-c9703cf48b6d?w=500',
    category: 'perfumes',
    subcategory: 'Men',
    material: 'Liquid',
    stock: 70,
    sku: 'PRD-001',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 115.0,
      },
      {
        size: '100ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 155.0,
      },
      {
        size: '30ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 20,
        price: 95.0,
      },
    ],
    featured: true,
  },
  {
    title: 'Prada Candy Eau de Parfum',
    brand: 'Prada',
    description: 'Sweet and sophisticated fragrance for women',
    price: 120.0,
    basePrice: 120.0,
    cover: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500',
    category: 'perfumes',
    subcategory: 'Women',
    material: 'Liquid',
    stock: 75,
    sku: 'PRD-002',
    weight: 0.2,
    dimensions: { length: 6, width: 6, height: 12 },
    variants: [
      {
        size: '50ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 120.0,
      },
      {
        size: '80ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 160.0,
      },
      {
        size: '30ml',
        color: 'Clear',
        colorCode: '#FFFFFF',
        stock: 25,
        price: 100.0,
      },
    ],
    featured: true,
  },
  // Zara Products
  {
    title: 'Zara Basic T-Shirt',
    brand: 'Zara',
    description: 'Cotton basic t-shirt for everyday wear',
    price: 19.99,
    basePrice: 19.99,
    cover: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    category: 'clothing',
    subcategory: 'Tops',
    material: 'Cotton',
    stock: 300,
    sku: 'ZAR-001',
    weight: 0.15,
    dimensions: { length: 30, width: 25, height: 2 },
    variants: [
      {
        size: 'XS',
        color: 'White',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 19.99,
      },
      {
        size: 'S',
        color: 'White',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 19.99,
      },
      {
        size: 'M',
        color: 'White',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 19.99,
      },
      {
        size: 'L',
        color: 'White',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 19.99,
      },
      {
        size: 'XL',
        color: 'White',
        colorCode: '#FFFFFF',
        stock: 50,
        price: 19.99,
      },
      {
        size: 'XS',
        color: 'Black',
        colorCode: '#000000',
        stock: 50,
        price: 19.99,
      },
    ],
    featured: false,
  },
  {
    title: 'Zara Slim Fit Jeans',
    brand: 'Zara',
    description: 'Classic slim fit jeans in denim',
    price: 49.99,
    basePrice: 49.99,
    cover: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
    category: 'clothing',
    subcategory: 'Bottoms',
    material: 'Denim',
    stock: 200,
    sku: 'ZAR-002',
    weight: 0.5,
    dimensions: { length: 35, width: 30, height: 5 },
    variants: [
      {
        size: '28',
        color: 'Blue',
        colorCode: '#4169E1',
        stock: 40,
        price: 49.99,
      },
      {
        size: '30',
        color: 'Blue',
        colorCode: '#4169E1',
        stock: 40,
        price: 49.99,
      },
      {
        size: '32',
        color: 'Blue',
        colorCode: '#4169E1',
        stock: 40,
        price: 49.99,
      },
      {
        size: '34',
        color: 'Blue',
        colorCode: '#4169E1',
        stock: 40,
        price: 49.99,
      },
      {
        size: '36',
        color: 'Blue',
        colorCode: '#4169E1',
        stock: 40,
        price: 49.99,
      },
    ],
    featured: false,
  },
  {
    title: 'Zara Leather Jacket',
    brand: 'Zara',
    description: 'Faux leather jacket with zip closure',
    price: 89.99,
    basePrice: 89.99,
    cover: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    category: 'clothing',
    subcategory: 'Outerwear',
    material: 'Faux Leather',
    stock: 80,
    sku: 'ZAR-003',
    weight: 0.8,
    dimensions: { length: 40, width: 35, height: 8 },
    variants: [
      {
        size: 'XS',
        color: 'Black',
        colorCode: '#000000',
        stock: 20,
        price: 89.99,
      },
      {
        size: 'S',
        color: 'Black',
        colorCode: '#000000',
        stock: 20,
        price: 89.99,
      },
      {
        size: 'M',
        color: 'Black',
        colorCode: '#000000',
        stock: 20,
        price: 89.99,
      },
      {
        size: 'L',
        color: 'Black',
        colorCode: '#000000',
        stock: 20,
        price: 89.99,
      },
    ],
    featured: true,
  },
];

async function seedDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(
      process.env.MONGO_URL || 'mongodb://localhost:27017/trendvaulta',
    );
    console.log('Connected to MongoDB');

    // Clear existing data
    await Brand.deleteMany({});
    await Product.deleteMany({});
    console.log('Cleared existing data');

    // Insert brands
    const brands = await Brand.insertMany(brandsData);
    console.log(`Inserted ${brands.length} brands`);

    // Create brand mapping
    const brandMap = {};
    brands.forEach((brand) => {
      brandMap[brand.name] = brand._id;
    });

    // Update products with brand IDs
    const productsWithBrandIds = productsData.map((product) => ({
      ...product,
      brand: brandMap[product.brand],
      averageRating: 4.5,
      reviewCount: Math.floor(Math.random() * 100) + 10,
    }));

    // Insert products
    const products = await Product.insertMany(productsWithBrandIds);
    console.log(`Inserted ${products.length} products`);

    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
